version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: arzuma_db
      POSTGRES_USER: arzuma_user
      POSTGRES_PASSWORD: arzuma_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432

  redis:
    image: redis:7
    container_name: redis
    restart: always

  backend:
    build: ./backend
    container_name: backend
    command: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    expose:
      - 8000

  frontend:
    build: ./SocialArt-FrontEnd/frontend
    container_name: frontend
    volumes:
      - ./SocialArt-FrontEnd/frontend:/app
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: 