# Generated by Django 5.2.4 on 2025-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in seconds (for videos)'),
        ),
    ]
