# Generated by Django 5.2.4 on 2025-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_trimmed',
            field=models.BooleanField(default=False, help_text='Whether video was trimmed in frontend'),
        ),
    ]
