# Generated by Django 5.2.4 on 2025-07-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='stripe_payment_intent',
        ),
    ]
